name: Get Version
  id: package
  run: echo "::set-output name=version::$(node -p "require('../../packages/svg/config.json').version")"
  shell: bash

name: Publish Package to npmjs
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: '18.16.0'
          registry-url: 'https://registry.npmjs.org'
      - run: yarn
      - run: yarn build
      - run: yarn version ${{ steps.package.outputs.version }}
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
